version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - psql_rails_7:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - db

volumes:
  psql_rails_7: